# Generated by Django 3.2.5 on 2021-09-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
